steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/hexagonalpipeline/smartfarm-be:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/hexagonalpipeline/smartfarm-be:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "smartfarm-be"
      - "--image"
      - "gcr.io/hexagonalpipeline/smartfarm-be:$COMMIT_SHA"
      - "--region"
      - "asia-northeast3"
images:
  - "gcr.io/hexagonalpipeline/smartfarm-be:$COMMIT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
