// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FarmPlot struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Location    pgtype.Text      `json:"location"`
	SizeSqm     int32            `json:"size_sqm"`
	MonthlyRent int32            `json:"monthly_rent"`
	CropType    pgtype.Text      `json:"crop_type"`
	Status      pgtype.Text      `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Raid struct {
	ID               int32            `json:"id"`
	Title            string           `json:"title"`
	Description      pgtype.Text      `json:"description"`
	CropType         string           `json:"crop_type"`
	TargetQuantity   int32            `json:"target_quantity"`
	MinParticipation int32            `json:"min_participation"`
	MaxParticipation int32            `json:"max_participation"`
	PricePerKg       int32            `json:"price_per_kg"`
	Deadline         pgtype.Timestamp `json:"deadline"`
	Status           pgtype.Text      `json:"status"`
	CreatorNickname  string           `json:"creator_nickname"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type RaidParticipation struct {
	ID                  int32            `json:"id"`
	RaidID              pgtype.Int4      `json:"raid_id"`
	ParticipantNickname string           `json:"participant_nickname"`
	Quantity            int32            `json:"quantity"`
	ExpectedRevenue     int32            `json:"expected_revenue"`
	Status              pgtype.Text      `json:"status"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
}

type Rental struct {
	ID             int32            `json:"id"`
	RenterNickname string           `json:"renter_nickname"`
	PlotID         pgtype.Int4      `json:"plot_id"`
	StartDate      pgtype.Date      `json:"start_date"`
	EndDate        pgtype.Date      `json:"end_date"`
	MonthlyRent    int32            `json:"monthly_rent"`
	Status         pgtype.Text      `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type RevenueRecord struct {
	ID          int32            `json:"id"`
	Nickname    string           `json:"nickname"`
	Type        string           `json:"type"`
	Amount      int32            `json:"amount"`
	SourceID    pgtype.Int4      `json:"source_id"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type UserStat struct {
	Nickname        string           `json:"nickname"`
	Level           pgtype.Int4      `json:"level"`
	Experience      pgtype.Int4      `json:"experience"`
	TotalRevenue    pgtype.Int4      `json:"total_revenue"`
	SuccessfulRaids pgtype.Int4      `json:"successful_raids"`
	PlotsRented     pgtype.Int4      `json:"plots_rented"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}
