// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: plant_card.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlantCard = `-- name: CreatePlantCard :one
INSERT INTO plant_cards (
    farm_plot_id,
    persona,
    image_url,
    video_url
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, farm_plot_id, persona, image_url, video_url, created_at
`

type CreatePlantCardParams struct {
	FarmPlotID int32       `json:"farm_plot_id"`
	Persona    string      `json:"persona"`
	ImageUrl   pgtype.Text `json:"image_url"`
	VideoUrl   pgtype.Text `json:"video_url"`
}

func (q *Queries) CreatePlantCard(ctx context.Context, arg CreatePlantCardParams) (PlantCard, error) {
	row := q.db.QueryRow(ctx, createPlantCard,
		arg.FarmPlotID,
		arg.Persona,
		arg.ImageUrl,
		arg.VideoUrl,
	)
	var i PlantCard
	err := row.Scan(
		&i.ID,
		&i.FarmPlotID,
		&i.Persona,
		&i.ImageUrl,
		&i.VideoUrl,
		&i.CreatedAt,
	)
	return i, err
}
