// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRaid(ctx context.Context, arg CreateRaidParams) (Raid, error)
	CreateRental(ctx context.Context, arg CreateRentalParams) (Rental, error)
	CreateUserStats(ctx context.Context, nickname string) (UserStat, error)
	GetLeaderboard(ctx context.Context) ([]GetLeaderboardRow, error)
	GetNicknameRaidHistory(ctx context.Context, participantNickname string) ([]GetNicknameRaidHistoryRow, error)
	GetNicknameRentals(ctx context.Context, renterNickname string) ([]GetNicknameRentalsRow, error)
	GetPlot(ctx context.Context, id int32) (FarmPlot, error)
	GetRaidDetails(ctx context.Context, id int32) (GetRaidDetailsRow, error)
	GetRaidParticipations(ctx context.Context, raidID int32) ([]GetRaidParticipationsRow, error)
	GetRental(ctx context.Context, id int32) (GetRentalRow, error)
	GetUserStats(ctx context.Context, nickname string) (UserStat, error)
	IncrementSuccessfulRaids(ctx context.Context, nickname string) (UserStat, error)
	JoinRaid(ctx context.Context, arg JoinRaidParams) (RaidParticipation, error)
	ListAvailablePlots(ctx context.Context) ([]FarmPlot, error)
	ListOpenRaids(ctx context.Context) ([]ListOpenRaidsRow, error)
	ListPlotsByCrop(ctx context.Context, cropType pgtype.Text) ([]FarmPlot, error)
	UpdatePlotStatus(ctx context.Context, arg UpdatePlotStatusParams) (FarmPlot, error)
	UpdateRaidStatus(ctx context.Context, arg UpdateRaidStatusParams) (Raid, error)
	UpdateUserExperience(ctx context.Context, arg UpdateUserExperienceParams) (UserStat, error)
	UpdateUserRevenue(ctx context.Context, arg UpdateUserRevenueParams) (UserStat, error)
}

var _ Querier = (*Queries)(nil)
